Tutorial\TotBundle\Entity\City:
    type: entity
    table: city
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        info:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
