<?php

namespace Tutorial\TotBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategTourConRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategTourConRepository extends EntityRepository
{
}
