<?php

namespace Tutorial\TotBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TourCategoryConn1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourCategoryConn1Repository extends EntityRepository
{
}
