categtourcon:
    pattern:  /
    defaults: { _controller: "TutorialTotBundle:CategTourCon:index" }

categtourcon_show:
    pattern:  /{id}/show
    defaults: { _controller: "TutorialTotBundle:CategTourCon:show" }

categtourcon_new:
    pattern:  /new
    defaults: { _controller: "TutorialTotBundle:CategTourCon:new" }

categtourcon_create:
    pattern:  /create
    defaults: { _controller: "TutorialTotBundle:CategTourCon:create" }
    requirements: { _method: post }

categtourcon_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TutorialTotBundle:CategTourCon:edit" }

categtourcon_update:
    pattern:  /{id}/update
    defaults: { _controller: "TutorialTotBundle:CategTourCon:update" }
    requirements: { _method: post|put }

categtourcon_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TutorialTotBundle:CategTourCon:delete" }
    requirements: { _method: post|delete }
